from dataclasses import dataclass
from dataclass_type_validator import dataclass_validate

from wing_snapfile.types.one_indexed_list import OneIndexedList

('sel', 1)
('mode', 'USER')
('cmode', 'PAN')
('gpio', {'1': {'bu': {'mode': 'OFF', 'name': 'GPIO 1'}}, '2': {'bu': {'mode': 'OFF', 'name': 'GPIO 2'}}, '3': {'bu': {'mode': 'OFF', 'name': 'GPIO 3'}}, '4': {'bu': {'mode': 'OFF', 'name': 'GPIO 4'}}})
('user', {'1': {'bu': {'mode': 'OFF', 'name': '', 'ledstate': 0}, 'bd': {'mode': 'OFF', 'name': '', 'ledstate': 0}}, '2': {'bu': {'mode': 'OFF', 'name': '', 'ledstate': 0}, 'bd': {'mode': 'OFF', 'name': '', 'ledstate': 0}}, '3': {'bu': {'mode': 'OFF', 'name': '', 'ledstate': 0}, 'bd': {'mode': 'OFF', 'name': '', 'ledstate': 0}}, '4': {'bu': {'mode': 'OFF', 'name': '', 'ledstate': 0}, 'bd': {'mode': 'OFF', 'name': '', 'ledstate': 0}}})
('daw1', {'1': {'bu': {'mode': 'DAWBTN', 'name': 'STOP', 'btn': 'T1'}, 'bd': {'mode': 'DAWBTN', 'name': 'REWIND', 'btn': 'T4'}}, '2': {'bu': {'mode': 'DAWBTN', 'name': 'PLAY', 'btn': 'T2'}, 'bd': {'mode': 'DAWBTN', 'name': 'FFWD', 'btn': 'T5'}}, '3': {'bu': {'mode': 'DAWBTN', 'name': 'CYCLE', 'btn': 'T8'}, 'bd': {'mode': 'DAWBTN', 'name': 'TIME/BEATS', 'btn': 'OT4'}}, '4': {'bu': {'mode': 'DAWBTN', 'name': 'RECORD', 'btn': 'T3'}, 'bd': {'mode': 'DAWBTN', 'name': '|UNDO', 'btn': 'SY6'}}})
('daw2', {'1': {'bu': {'mode': 'DAWBTN', 'name': 'STOP', 'btn': 'T1'}, 'bd': {'mode': 'DAWBTN', 'name': 'REWIND/PREV', 'btn': 'T4'}}, '2': {'bu': {'mode': 'DAWBTN', 'name': 'PLAY', 'btn': 'T2'}, 'bd': {'mode': 'DAWBTN', 'name': 'FFWD/NEXT', 'btn': 'T5'}}, '3': {'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '4': {'bu': {'mode': 'DAWBTN', 'name': 'RECORD', 'btn': 'T3'}, 'bd': {'mode': 'DAWBTN', 'name': '|EDIT MARKER', 'btn': 'T6'}}})
('daw3', {'1': {'bu': {'mode': 'DAWBTN', 'name': 'STOP', 'btn': 'T1'}, 'bd': {'mode': 'DAWBTN', 'name': 'REWIND', 'btn': 'T4'}}, '2': {'bu': {'mode': 'DAWBTN', 'name': 'PLAY', 'btn': 'T2'}, 'bd': {'mode': 'DAWBTN', 'name': 'FFWD', 'btn': 'T5'}}, '3': {'bu': {'mode': 'DAWBTN', 'name': ' |TOUCH', 'btn': 'AU4'}, 'bd': {'mode': 'DAWBTN', 'name': '|READ', 'btn': 'AU1'}}, '4': {'bu': {'mode': 'DAWBTN', 'name': ' |LATCH', 'btn': 'AU5'}, 'bd': {'mode': 'DAWBTN', 'name': '|WRITE', 'btn': 'AU2'}}})
('daw4', {'1': {'bu': {'mode': 'DAWBTN', 'name': 'NAME/VALUE', 'btn': 'OT3'}, 'bd': {'mode': 'DAWBTN', 'name': 'FLIP', 'btn': 'OT1'}}, '2': {'bu': {'mode': 'OFF', 'name': '[V-POTS]'}, 'bd': {'mode': 'DAWBTN', 'name': 'HOLD |SEL', 'btn': 'SP2'}}, '3': {'bu': {'mode': 'OFF', 'name': '[RECRDY]'}, 'bd': {'mode': 'DAWBTN', 'name': '[HOLD+] |SEL', 'btn': 'SP3'}}, '4': {'bu': {'mode': 'DAWBTN', 'name': 'ZOOM', 'btn': 'N5'}, 'bd': {'mode': 'DAWBTN', 'name': 'SCRUB', 'btn': 'T11'}}})
('1', {'1': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': '', 'ledstate': 0}, 'bu': {'mode': 'OFF', 'name': '', 'ledstate': 0}, 'bd': {'mode': 'OFF', 'name': '', 'ledstate': 0}}, '2': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': '', 'ledstate': 0}, 'bu': {'mode': 'OFF', 'name': '', 'ledstate': 0}, 'bd': {'mode': 'OFF', 'name': '', 'ledstate': 0}}, '3': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': '', 'ledstate': 0}, 'bu': {'mode': 'OFF', 'name': '', 'ledstate': 0}, 'bd': {'mode': 'OFF', 'name': '', 'ledstate': 0}}, '4': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': '', 'ledstate': 0}, 'bu': {'mode': 'OFF', 'name': '', 'ledstate': 0}, 'bd': {'mode': 'OFF', 'name': '', 'ledstate': 0}}})
('2', {'1': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}})
('3', {'1': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}})
('4', {'1': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}})
('5', {'1': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}})
('6', {'1': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}})
('7', {'1': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}})
('8', {'1': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}})
('9', {'1': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}})
('10', {'1': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}})
('11', {'1': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}})
('12', {'1': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}})
('13', {'1': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}})
('14', {'1': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}})
('15', {'1': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}})
('16', {'1': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'enc': {'mode': 'OFF', 'name': ''}, 'bu': {'mode': 'OFF', 'name': ''}, 'bd': {'mode': 'OFF', 'name': ''}}})
('U1', {'1': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}})
('U2', {'1': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}})
('U3', {'1': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}})
('U4', {'1': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}})
('MM', {'1': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}})
('D1', {'1': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}})
('D2', {'1': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}})
('D3', {'1': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}})
('D4', {'1': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '2': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '3': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}, '4': {'led': False, 'col': 1, 'bu': {'mode': 'OFF', 'name': ''}}})
('cuser', {'1': 1, '2': 1, '3': 1})

@dataclass_validate
@dataclass(kw_only=True)
class UpperButtonSettings:
    mode: str
    name: str

@dataclass_validate
@dataclass(kw_only=True)
class User:
    user_select: int
    user_button_mode: str
    user_channel_mode: str
    gpio: OneIndexedList[dict]
    user_layer: dict
    daw_button_settings: OneIndexedList[dict]
    user_buttons_and_encoders: OneIndexedList[dict]
    user_layer_buttons_compact: OneIndexedList[dict]
    main_matrix_layer_buttons_5_8_compact: OneIndexedList[dict]
    dca_layer_buttons_compact: OneIndexedList[dict]
    cuser_rotary_knob_positions: OneIndexedList[int]